/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_renderer_canvas_NativeLayer */

#ifndef _Included_test_renderer_canvas_NativeLayer
#define _Included_test_renderer_canvas_NativeLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_renderer_canvas_NativeLayer
 * Method:    NativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_renderer_canvas_NativeLayer_NativeInit
  (JNIEnv *, jclass);

/*
 * Class:     test_renderer_canvas_NativeLayer
 * Method:    NativeSetup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_test_renderer_canvas_NativeLayer_NativeSetup
  (JNIEnv *, jobject);

/*
 * Class:     test_renderer_canvas_NativeLayer
 * Method:    NativeRender
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_test_renderer_canvas_NativeLayer_NativeRender
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
